# Generated by Django 5.0.6 on 2024-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
