# Generated by Django 5.0.6 on 2024-07-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_private_privatechat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='private',
            old_name='u_name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='privatechat',
            old_name='u_name',
            new_name='user',
        ),
    ]
